AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  S3MetadataAPIAppS3MetadataAPI1XKG83ES9NPKN:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 30
      Role: >-
        arn:aws:iam::655743737011:role/S3-Metadata-API-AppS3MetadataAPIRole-1WGCMUF1PX6S8
      Environment:
        Variables:
          MONGODB_URI: >-
            mongodb+srv://s3-admin:s3-admin@teste-s3.rfk4x.mongodb.net/historico?retryWrites=true&w=majority
      Tags:
        'lambda:createdBy': SAM
